
import os
import sys

import scripts.setup_snakemake as setup
import input_manager as im

include: "rules/initialize.smk"

include: "rules/raw_reads_processing.smk"
include: "rules/reads_to_reference_genome_processing.smk"

rule all:
    input:
        lambda wildcards: im.get_all_inputs(config["species"])

