################################################
# Snakefile for aDNA Pipeline
################################################
# This Snakefile orchestrates the workflow for aDNA reads analysis.
# It includes rules for different processing steps, such as raw read processing, mapping to reference, and quality control.

# initialize_pipeline.smk: Sets up initial configurations and outputs 
# information for the pipeline.
include: "rules/initialize.smk"

# file_manager.py: Manages file paths and directories.
include: "scripts/file_manager.py"

# expected_output_manager.py: Manages expected output of pipeline 
# and requests the files for rule all
include: "scripts/expected_output_manager.py"

# rules/raw_reads_processing.smk: Contains rules for processing raw aDNA reads.
include: "rules/raw_reads_processing.smk"

# rules/reads_to_reference_processing.smk: Contains rules for mapping reads to reference.
include: "rules/reads_to_reference_processing.smk"

# Define the all rule to specify the final targets of the workflow
# This rule ensures that all necessary processing is completed for each species
rule all:
    input:
        # this python function from expected_output_manager.py gives us all requested outputs.
        # thus, the pipeline is triggered.
        get_expected_outputs_from_pipeline

# Add logging for workflow completion
onsuccess:
    logger.info("Workflow finished, no error")

# Add logging for workflow errors
onerror:
    logger.error("An error occurred")