
import os
import sys

include: "rules/initialize.smk"
include: "scripts/input_manager.py"

include: "rules/raw_reads_processing.smk"
include: "rules/reads_to_reference_genome_processing.smk"

rule all:
    input:
        get_all_inputs

