def generate_multiqc_config_for_species_and_individual(species, individual):

    return (
        f"# MultiQC configuration for species: {species}, individual: {individual}\n"
        f"title: 'PastForward Report for species {species}, individual {individual}'\n"
       # f"subtitle: \"Results overview for species {species}, individual {individual} from PastForward Pipeline\"\n"
        f"intro_text: 'This MultiQC report summarises the results for species {species}, individual {individual} processed with the PastForward.'\n"
        "\n"
        "custom_data:\n"
        "   ecmsd_unique_taxa:\n"
        "       parent_id: ecmsd\n"
        "       parent_name: 'ECMSD Contamination Analysis'\n"
        "       section_name: 'ECMSD Mitochondrial Hits'\n"
        "       description: 'Relative abundance of mitochondrial reads assigned to different genera. Note that below contamination values only reflect the proportion of reads that have been identified as mitochondrial reads by ECMSD. These do not represent the complete set of reads of the sample.'\n"
        "       file_format: 'tsv'\n"
        "       plot_type: 'bargraph'\n"
        "       pconfig:\n"
        "           id: 'ecmsd_proportions_plot'\n"
        "           title: 'ECMSD Mitochondrial Hits'\n"
        "           ylab: 'Reads'\n"
        "           xlab: 'Taxa'\n"
        "           sort_samples: false\n"
        "           tt_decimals: 0\n"
        "           stacking: 'relative'\n"
        "           cpswitch_c_active: false\n"
        "           cpswitch_counts_label: 'Read Counts'\n"
        "           cpswitch_percent_label: 'Percentages'\n"
        "\n"
        # "   ecmsd_readlengths:\n"
        # "       parent_id: ecmsd\n"
        # "       parent_name: 'ECMSD Contamination Analysis'\n"
        # "       section_name: 'ECMSD Read Lengths'\n"
        # "       description: 'Distribution of read lengths across genera to evaluate contamination and distinguish ancient from modern read.'\n"
        # "       file_format: 'png'\n"
        # "\n"
        # "   ecmsd_proportions_overall_reads:\n"
        # "       parent_id: ecmsd\n"
        # "       parent_name: 'ECMSD Contamination Analysis'\n"
        # "       section_name: 'ECMSD Proportions Overview'\n"
        # "       description: 'Proportions of reads assigned to mitochondrial dna in relation to total reads of sample. Classified reads are further specified in the \"ECMSD Mitochondrial Hits\" section.'\n"
        # "       file_format: 'tsv'\n"
        # "       plot_type: 'bargraph'\n"
        # "       pconfig:\n"
        # "           id: 'ecmsd_proportions_overall_reads_plot'\n"
        # "           title: 'ECMSD Mitochondrial DNA Proportions Overview'\n"
        # "           ylab: 'Sample'\n"
        # "           xlab: 'Reads'\n"
        # "           stacking: 'relative'\n"
        # "           cpswitch_c_active: false\n"
        # "           cpswitch_counts_label: 'Read Counts'\n"
        # "           cpswitch_percent_label: 'Percentages'\n"
        # "\n"
        # "   centrifuge_proportions:\n"
        # "       parent_id: centrifuge\n"
        # "       parent_name: 'Centrifuge Taxonomic Classification'\n"
        # "       section_name: 'Centrifuge contamination overview'\n"
        # "       description: 'Proportions of reads classified by Centrifuge to unclassified. Classified reads are further specified '\n"
        # "       file_format: 'tsv'\n"
        # "       plot_type: 'bargraph'\n"
        # "       pconfig:\n"
        # "           id: 'centrifuge_proportions_plot'\n"
        # "           title: 'Centrifuge Contamination Overview'\n"
        # "           ylab: 'Reads'\n"
        # "           xlab: 'Taxa'\n"
        # "           stacking: 'relative'\n"
        # "           cpswitch_c_active: false\n"
        # "           cpswitch_counts_label: 'Read Counts'\n"
        # "           cpswitch_percent_label: 'Percentages'\n"
        # "\n"
        # "   centrifuge_unique:\n"
        # "       parent_id: centrifuge\n"
        # "       parent_name: 'Centrifuge Taxonomic Classification'\n"
        # "       section_name: 'Centrifuge Top 10 Unique Reads'\n"
        # "       description: 'Top 10 taxa based on unique reads; remaining taxa are grouped in Others.'\n"
        # "       file_format: 'tsv'\n"
        # "       plot_type: 'bargraph'\n"
        # "       pconfig:\n"
        # "           id: 'centrifuge_unique_plot'\n"
        # "           title: 'Top 10 Taxa (Unique Reads)'\n"
        # "           ylab: 'Reads'\n"
        # "           xlab: 'Taxa'\n"
        # "           stacking: 'relative'\n"
        # "           cpswitch_c_active: false\n"
        # "           cpswitch_counts_label: 'Read Counts'\n"
        # "           cpswitch_percent_label: 'Percentages'\n"
        # "\n"
        "   centrifuge_total:\n"
        "       parent_id: centrifuge\n"
        "       parent_name: 'Centrifuge Taxonomic Classification'\n"
        "       section_name: 'Centrifuge Top 10 Total Reads'\n"
        "       description: 'Top 10 taxa based on total reads; remaining taxa are grouped in category \"Others\". The contamination values reflect the proportion of reads that have been identified as contamination by Centrifuge. These do not represent the complete set of reads of the sample.'\n"
        "       file_format: 'tsv'\n"
        "       plot_type: 'bargraph'\n"
        "       pconfig:\n"
        "           id: 'centrifuge_total_plot'\n"
        "           title: 'Top 10 Taxa (Total Reads)'\n"
        "           ylab: 'Reads'\n"
        "           xlab: 'Taxa'\n"
        "           stacking: 'relative'\n"
        "           cpswitch_c_active: false\n"
        "           cpswitch_counts_label: 'Read Counts'\n"
        "           cpswitch_percent_label: 'Percentages'\n"
        "\n"
        "   coverage_table:\n"        
        "       parent_id: depth_breadth\n"
        "       parent_name: 'Depth and Breadth Coverage'\n"
        "       section_name: 'Coverage Overview'\n"
        "       description: 'Overview of depth and breadth coverage across the reference. Breadth is defined as the fraction of the reference genome that is covered by at least one read. Depth is defined as the number of reads that cover each base of the reference genome. Below table shows the coverage statistics for each sample.'\n"
        "       file_format: 'tsv'\n"
        "       plot_type: 'table'\n"
        "\n"
        # "   depth_coverage:\n"        
        # "       parent_id: depth_breadth\n"
        # "       parent_name: 'Depth and Breadth Coverage'\n"
        # "       section_name: 'Depth Coverage'\n"
        # "       description: 'Depth of coverage across the reference genome.'\n"
        # "       file_format: 'csv'\n"
        # "       plot_type: 'linegraph'\n"
        # "       pconfig:\n"
        # "           id: 'depth_coverage_plot'\n"
        # "           title: 'Depth Coverage of Reference'\n"
        # "           logswitch: true\n"
        # "           logswitch_active: true\n"
        # "           xlog: true\n"
        # "           ylog: true\n"
        # "\n"
        "   breadth_coverage:\n"        
        "       parent_id: depth_breadth\n"
        "       parent_name: 'Depth and Breadth Coverage'\n"
        "       section_name: 'Breadth Coverage'\n"
        "       description: 'Breadth coverage across the reference. Breadth is defined as the fraction of the reference genome that is covered by at least one read.'\n"
        "       file_format: 'tsv'\n"
        "       plot_type: 'bargraph'\n"
        "       categories:\n"
        "          covered_bases:\n"
        "            name: 'Covered Bases'\n"
        "            color: '#457cb2'\n"
        "          uncovered_bases:\n"
        "            name: 'Uncovered Bases'\n"
        "            color: '#bdc3c7'\n"
        "       pconfig:\n"
        "           id: 'breadth_coverage_plot'\n"
        "           title: 'Breadth Coverage of Reference'\n"
        "           ylab: 'Coverage of reference'\n"
        "           sort_samples: false\n"
        "           tt_decimals: 0\n"
        "           stacking: 'relative'\n"
        "           cpswitch_c_active: false\n"
        "           cpswitch_counts_label: 'Read Counts'\n"
        "           cpswitch_percent_label: 'Percentages'\n"
        "\n"
        "   endogenous_total:\n"
        "       parent_id: endogenous\n"
        "       parent_name: 'Endogenous Reads'\n"
        "       section_name: 'Endogenous Total Reads'\n"
        "       description: 'This plot summarizes the number of reads from post-processing until endogenous reads. This includes all steps from raw reads to endogenous reads.'\n"
        "       file_format: 'tsv'\n"
        "       plot_type: 'bargraph'\n"
        "       categories:\n"
        "          endogenous_duplicates_removed:\n"
        "            name: 'Endogenous Reads (w.o. Duplicates)'\n"
        "            color: '#457cb2'\n"
        "          mapped_endogenous_reads:\n"
        "            name: 'Endogenous Reads (w. Duplicates)'\n"
        "            color: '#1e4d7b'\n"
        "          after_quality_filter:\n"
        "            name: 'Unmapped Reads (after Quality Filtering)'\n"
        "            color: '#bdc3c7'\n"
        "          after_adapter_removed:\n"
        "            name: 'Unmapped Reads (after Adapter Removal)'\n"
        "            color: '#95a5a6'\n"
        "          raw_reads:\n"
        "            name: 'Raw Reads'\n"
        "            color: '#7f8c8d'\n"
        "       pconfig:\n"
        "           id: 'reads_endogenous_plot'\n"
        "           title: 'Endogenous Reads'\n"
        "           ylab: 'Reads'\n"
        "           xlab: 'Step'\n"
        "           sort_samples: false\n"
        "           tt_decimals: 0\n"
        "           stacking: 'group'\n"
        "           cpswitch: false\n"
        "\n"
        "   endogenous_stacked:\n"
        "       parent_id: endogenous\n"
        "       parent_name: 'Endogenous Reads'\n"
        "       section_name: 'Endogenous Reads Stacked'\n"
        "       description: 'This plot shows the stacked distribution of mapped reads and unmapped reads. mapped reads are those that align to the reference genome and are considered endogenous. Additionally, endogenous reads are checked for duplicates. The duplicates are then removed. Their proportions are shown in the plot as well.'\n"
        "       file_format: 'tsv'\n"
        "       plot_type: 'bargraph'\n"
        "       categories:\n"
        "          endogenous:\n"
        "            name: 'Endogenous Reads'\n"
        "            color: '#457cb2'\n"
        "          duplicates:\n"
        "            name: 'Duplicates Removed'\n"
        "            color: '#f49393'\n"
        "          non_endogenous:\n"
        "            name: 'Unmapped Reads'\n"
        "            color: '#bdc3c7'\n"
        "       pconfig:\n"
        "           id: 'reads_endogenous_stacked_plot'\n"
        "           title: 'Endogenous Reads Stacked'\n"
        "           ylab: 'Reads'\n"
        "           xlab: 'Step'\n"
        "           sort_samples: false\n"
        "           tt_decimals: 0\n"
        "           stacking: 'relative'\n"
        "           cpswitch_c_active: false\n"
        "           cpswitch_counts_label: 'Read Counts'\n"
        "           cpswitch_percent_label: 'Percentages'\n"
        "\n"
        "sp:\n"
        # "   ecmsd_readlengths:\n"
        # "       fn: '*_Mito_summary_genus_ReadLengths.png'\n"
        "   ecmsd_unique_taxa:\n"
        "       fn: '*_Mito_summary_genus_hits_combined.tsv'\n"
        # "   ecmsd_proportions_overall_reads:\n"
        # "       fn: '*_ecmsd_proportions.tsv'\n"
        # "   depth_coverage:\n"
        # "       fn: '*_depth_coverage_*.csv'\n"
        "   endogenous_total:\n"
        "       fn: '*_reads_processing_summary.tsv'\n"
        "   endogenous_stacked:\n"
        "       fn: '*_reads_processing_summary_stacked.tsv'\n"
        "   breadth_coverage:\n"
        "       fn: '*_coverage_analysis.tsv'\n"
        "   coverage_table:\n"
        "       fn: '*_coverage_summary.tsv'\n"
        # "   centrifuge_proportions:\n"
        # "       fn: '*_centrifuge_proportions.tsv'\n"
        # "   centrifuge_unique:\n"
        # "       fn: '*_top10_unique_taxa.tsv'\n"
        "   centrifuge_total:\n"
        "       fn: '*_top10_total_taxa.tsv'\n"
        "\n"
        "ignore_images: false\n"
        "module_order:\n"
        "   - fastqc:\n"
        "       name: 'FastQC (raw)'\n"
        "       anchor: 'fastqc_raw'\n"
        "       info: 'This section of the report shows FastQC results for the raw reads.'\n"
        "       path_filters:\n"
        "         - '*_raw_fastqc.zip'\n"
        "       remove_section:\n"
        "   - fastqc:\n"
        "       name: 'FastQC (adapter removed)'\n"
        "       anchor: 'fastqc_trimmed'\n"
        "       info: 'This section of the report shows FastQC results after adapter trimming.'\n"
        "       target: ''\n"
        "       path_filters:\n"
        "         - '*_trimmed_fastqc.zip'\n"
        "   - fastqc:\n"
        "       name: 'FastQC (quality filtered)'\n"
        "       anchor: 'fastqc_filtered'\n"
        "       info: 'This section of the report shows FastQC results after quality filtering.'\n"
        "       target: ''\n"
        "       path_filters:\n"
        "         - '*_quality_filtered_fastqc.zip'\n"
        "   - fastqc:\n"
        "       name: 'FastQC (merged)'\n"
        "       anchor: 'fastqc_merged'\n"
        "       info: 'This section of the report shows FastQC results after merging.'\n"
        "       target: ''\n"
        "       path_filters:\n"
        "         - '*_merged_fastqc.zip'\n"
        "   - fastp:\n"
        "       name: 'Fastp (adapter removal)'\n"
        "       anchor: 'fastp_adapter_removal'\n"
        "       info: 'This section of the report shows FastP results of adapter trimming.'\n"
        "       target: ''\n"
        "       path_filters:\n"
        "         - '*_trimmed.*.json'\n"
        "   - fastp:\n"
        "       name: 'Fastp (quality filtering)'\n"
        "       anchor: 'fastp_quality_filtered'\n"
        "       info: 'This section of the report shows FastP results of quality filtering.'\n"
        "       target: ''\n"
        "       path_filters:\n"
        "         - '*_quality_filtered.json'\n"
        "report_section_order:\n"
        "   fastqc_raw:\n"
        "       order: 130\n"
        "   fastp_adapter_removal:\n"
        "       order: 120\n"
        "   fastqc_trimmed:\n"
        "       order: 110\n"
        "   fastp_quality_filtered:\n"
        "       order: 100\n"
        "   fastqc_filtered:\n"
        "       order: 90\n"
        "   fastqc_merged:\n"
        "       order: 80\n"
        "   ecmsd:\n"
        "       order: 70\n"
        "   centrifuge:\n"
        "       order: 65\n"
        "   endogenous:\n"
        "       order: 62\n"
        "   depth_breadth:\n"
        "       order: 61\n"
        "   qualimap:\n"
        "       order: 60\n"
        "   samtools:\n"
        "       order: 50\n"
        "   dedup:\n"
        "       order: 40\n"
        "   picard:\n"
        "       order: 30\n"
        "   preseq:\n"
        "       order: 20\n"
        "   mapdamage:\n"
        "       order: 10\n"
        "remove_sections:\n"
        "   - fastqc_merged_fastqc_sequence_counts\n"
        "   - fastqc_merged_fastqc_per_sequence_quality_scores\n" 
        "   - fastqc_merged_fastqc_merged_per_base_sequence_content\n"
        "   - fastqc_merged_fastqc_per_sequence_gc_content\n"
        "   - fastqc_merged_fastqc_per_base_n_content\n"
        "   - fastqc_merged_fastqc_sequence_duplication_levels\n"
        "   - fastqc_merged_fastqc_overrepresented_sequences\n"
        "   - fastqc_merged_fastqc_top_overrepresented_sequences\n"
        "   - fastqc_merged_fastqc_adapter_content\n"
        "   - fastqc_merged_fastqc_status_checks\n"
        "   - mapdamage-forward-read-length-distribution\n"
        "   - mapdamage-reverse-read-length-distribution\n"
        "   - qualimap-gc-distribution\n"
        "   - samtools-stats\n"
        "# remove from file name in report\n"
        "extra_fn_clean_exts:\n"
        "   - type: regex_keep\n"
        "     pattern: \"^[^_]+\"\n"
        "table_columns_visible:\n"
        "   FastQC (merged):\n"
        "       percent_duplicates: false\n"
        "       percent_gc: false\n"
        "       total_sequences: false\n"
        "   'QualiMap: BamQC':\n"
        "       percentage_aligned: false\n"
        "       duplication_rate: false\n"
        "       1_x_pc: false\n"
        "       5_x_pc: true\n"
        "       10_x_pc: true\n"
        "   'Samtools: stats':\n"
        "       non_primary_alignments: false\n"
        "       error_rate: false\n"
        "       reads_MQ0_percent: true\n"
    )

species = snakemake.wildcards.species
individual = snakemake.wildcards.get("individual", "overall")

# Generate the MultiQC config content
config_content = generate_multiqc_config_for_species_and_individual(species, individual)

# Write to output file
with open(snakemake.output[0], 'w') as f:
    f.write(config_content)